enum EquipmentState{running,standby,maintenance,outOfService,taggedOut}
enum Priority{normal,important,critical}
enum ActionState{open,inProgress,waiting,completed}
class Equipment{final String tag,name,area;EquipmentState state;String note;Equipment({required this.tag,required this.name,required this.area,this.state=EquipmentState.running,this.note=''});Map<String,dynamic> toJson()=>{'tag':tag,'name':name,'area':area,'state':state.name,'note':note};factory Equipment.fromJson(Map<String,dynamic> j)=>Equipment(tag:j['tag']??'',name:j['name']??'',area:j['area']??'',state:EquipmentState.values.firstWhere((e)=>e.name==j['state'],orElse:()=>EquipmentState.running),note:j['note']??'');}
class LogEntry{final String id,text;final DateTime createdAt;final String? equipmentTag;final Priority priority;final String source;LogEntry({required this.id,required this.createdAt,required this.text,this.equipmentTag,this.priority=Priority.normal,this.source='manual'});Map<String,dynamic> toJson()=>{'id':id,'createdAt':createdAt.toIso8601String(),'text':text,'equipmentTag':equipmentTag,'priority':priority.name,'source':source};factory LogEntry.fromJson(Map<String,dynamic> j)=>LogEntry(id:j['id']??'',createdAt:DateTime.tryParse(j['createdAt']??'')??DateTime.now(),text:j['text']??'',equipmentTag:j['equipmentTag'],priority:Priority.values.firstWhere((e)=>e.name==j['priority'],orElse:()=>Priority.normal),source:j['source']??'manual');}
class WatchItem{final String id,title,detail;final String? equipmentTag;bool active;WatchItem({required this.id,required this.title,required this.detail,this.equipmentTag,this.active=true});Map<String,dynamic> toJson()=>{'id':id,'title':title,'detail':detail,'equipmentTag':equipmentTag,'active':active};factory WatchItem.fromJson(Map<String,dynamic> j)=>WatchItem(id:j['id']??'',title:j['title']??'',detail:j['detail']??'',equipmentTag:j['equipmentTag'],active:j['active']??true);}
class OperatorTask{final String id,title;final String? equipmentTag;final DateTime createdAt;DateTime? dueAt;ActionState state;int carriedShifts;OperatorTask({required this.id,required this.title,this.equipmentTag,DateTime? createdAt,this.dueAt,this.state=ActionState.open,this.carriedShifts=0}):createdAt=createdAt??DateTime.now();bool get overdue=>dueAt!=null&&state!=ActionState.completed&&DateTime.now().isAfter(dueAt!);Map<String,dynamic> toJson()=>{'id':id,'title':title,'equipmentTag':equipmentTag,'createdAt':createdAt.toIso8601String(),'dueAt':dueAt?.toIso8601String(),'state':state.name,'carriedShifts':carriedShifts};factory OperatorTask.fromJson(Map<String,dynamic> j)=>OperatorTask(id:j['id']??'',title:j['title']??'',equipmentTag:j['equipmentTag'],createdAt:DateTime.tryParse(j['createdAt']??''),dueAt:j['dueAt']==null?null:DateTime.tryParse(j['dueAt']),state:ActionState.values.firstWhere((e)=>e.name==j['state'],orElse:()=>ActionState.open),carriedShifts:j['carriedShifts']??0);}
class ProcedureItem{final String title,category,source;const ProcedureItem(this.title,this.category,this.source);}

enum ShiftType{morning,afternoon,night,custom}
class ShiftSession{final String id,operatorName;final ShiftType type;final DateTime startedAt;DateTime? endedAt;final int openingLogIndex;ShiftSession({required this.id,required this.operatorName,required this.type,required this.startedAt,this.endedAt,this.openingLogIndex=0});bool get active=>endedAt==null;Map<String,dynamic> toJson()=>{'id':id,'operatorName':operatorName,'type':type.name,'startedAt':startedAt.toIso8601String(),'endedAt':endedAt?.toIso8601String(),'openingLogIndex':openingLogIndex};factory ShiftSession.fromJson(Map<String,dynamic> j)=>ShiftSession(id:j['id']??'',operatorName:j['operatorName']??'',type:ShiftType.values.firstWhere((e)=>e.name==j['type'],orElse:()=>ShiftType.custom),startedAt:DateTime.tryParse(j['startedAt']??'')??DateTime.now(),endedAt:j['endedAt']==null?null:DateTime.tryParse(j['endedAt']),openingLogIndex:j['openingLogIndex']??0);}
