import 'package:flutter/material.dart';import '../data/app_store.dart';import '../data/timer_repository.dart';import '../models/models.dart';import '../models/operator_timer.dart';import '../models/shift_handover.dart';import '../theme/operon_theme.dart';import '../widgets/common.dart';
class HandoverScreen extends StatefulWidget{final AppStore store;const HandoverScreen({super.key,required this.store});@override State<HandoverScreen> createState()=>_S();}
class _S extends State<HandoverScreen>{List<OperatorTimer> timers=[];final notes=TextEditingController(),incoming=TextEditingController();@override void initState(){super.initState();TimerRepository().load().then((x){if(mounted)setState(()=>timers=x);});}
@override Widget build(BuildContext c){final open=widget.store.tasks.where((x)=>x.state!=ActionState.completed).toList(),maint=widget.store.equipment.where((x)=>x.state==EquipmentState.maintenance||x.state==EquipmentState.outOfService||x.state==EquipmentState.taggedOut).toList(),watch=widget.store.watch.where((x)=>x.active).toList(),activeTimers=timers.where((x)=>x.active).toList(),pending=widget.store.pendingHandover;return Scaffold(appBar:AppBar(title:const Text('Shift handover')),body:ListView(padding:const EdgeInsets.only(bottom:30),children:[
 if(pending!=null)Card(margin:const EdgeInsets.all(16),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('HANDOVER WAITING FOR ACCEPTANCE',style:TextStyle(color:OperonTheme.teal,fontWeight:FontWeight.w800)),const SizedBox(height:6),Text('${pending.outgoingOperator} · ${pending.outgoingShift}'),const SizedBox(height:12),TextField(controller:incoming,decoration:const InputDecoration(labelText:'Incoming operator')),const SizedBox(height:10),FilledButton.icon(onPressed:()=>_accept(pending),icon:const Icon(Icons.verified),label:const Text('Accept handover'))]))),
 const SectionLabel('Open actions'),...open.map((e)=>ListTile(title:Text(e.title),subtitle:Text(e.equipmentTag??'General'))),const SectionLabel('Equipment unavailable / maintenance'),...maint.map((e)=>ListTile(title:Text(e.tag),subtitle:Text('${e.name} · ${e.state.name}'))),const SectionLabel('Watch items'),...watch.map((e)=>ListTile(title:Text(e.equipmentTag??e.title),subtitle:Text('${e.title} · ${e.detail}'))),const SectionLabel('Timers / reminders'),if(activeTimers.isEmpty)const ListTile(title:Text('No active timers')),...activeTimers.map((e)=>ListTile(title:Text(e.title),subtitle:Text('${e.equipmentTag??'General'} · due ${hhmm(e.dueAt)} · ${e.acknowledged?'acknowledged':'needs acknowledgement'}'))),
 Padding(padding:const EdgeInsets.all(16),child:TextField(controller:notes,maxLines:3,decoration:const InputDecoration(labelText:'Handover notes'))),
 if(widget.store.currentShift?.active==true&&pending==null)Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:FilledButton.icon(onPressed:()=>_prepare(open,maint,watch,activeTimers),icon:const Icon(Icons.handshake),label:const Text('Prepare handover'))),
 const SectionLabel('Handover history'),...widget.store.handovers.take(8).map((h)=>ListTile(leading:Icon(h.accepted?Icons.verified:Icons.schedule,color:h.accepted?OperonTheme.teal:Colors.orange),title:Text('${h.outgoingOperator} → ${h.incomingOperator??'Pending'}'),subtitle:Text('${h.outgoingShift} · ${h.accepted?'Accepted ${hhmm(h.acceptedAt!)}':'Awaiting acceptance'}')))
 ]));}
 void _prepare(List<OperatorTask> open,List<Equipment> maint,List<WatchItem> watch,List<OperatorTimer> ts){final s=widget.store.currentShift!;widget.store.saveHandover(ShiftHandover(id:DateTime.now().microsecondsSinceEpoch.toString(),createdAt:DateTime.now(),outgoingOperator:s.operatorName,outgoingShift:s.type.name,openItems:open.map((e)=>'${e.equipmentTag??'General'} · ${e.title}').toList(),maintenance:maint.map((e)=>'${e.tag} · ${e.state.name}').toList(),watchItems:watch.map((e)=>'${e.equipmentTag??'General'} · ${e.detail}').toList(),timers:ts.map((e)=>'${e.equipmentTag??'General'} · ${e.title}').toList(),notes:notes.text.trim()));setState((){});}
 void _accept(ShiftHandover h){if(incoming.text.trim().isEmpty)return;widget.store.acceptHandover(h,incoming.text);setState((){});}
}
