import 'dart:async';import 'package:flutter/material.dart';import '../models/operator_timer.dart';import '../data/timer_repository.dart';import '../services/notification_service.dart';import '../theme/operon_theme.dart';
class TimersScreen extends StatefulWidget{const TimersScreen({super.key});@override State<TimersScreen> createState()=>_S();}
class _S extends State<TimersScreen>{final timers=<OperatorTimer>[];Timer? tick;final repo=TimerRepository();@override void initState(){super.initState();_load();NotificationService.instance.requestPermissions();tick=Timer.periodic(const Duration(seconds:1),(_)=>_pulse());}@override void dispose(){tick?.cancel();super.dispose();}
Future<void> _load()async{timers..clear()..addAll(await repo.load());if(mounted)setState((){});}Future<void> _save()=>repo.save(timers);
void _pulse(){var dirty=false;for(final t in timers.where((x)=>x.due&&!x.notificationSent)){t.notificationSent=true;NotificationService.instance.showDue(t.id,t.title,t.equipmentTag);dirty=true;}if(dirty)_save();if(mounted)setState((){});}
@override Widget build(BuildContext c){final active=timers.where((x)=>x.active).toList(),done=timers.where((x)=>x.completed).toList();return Scaffold(appBar:AppBar(title:const Text('Timers & reminders')),body:ListView(padding:const EdgeInsets.all(12),children:[if(active.isEmpty)const ListTile(title:Text('No active timers')),...active.map(_card),if(done.isNotEmpty)...[const Padding(padding:EdgeInsets.fromLTRB(8,20,8,6),child:Text('COMPLETED',style:TextStyle(color:OperonTheme.muted,fontWeight:FontWeight.w800,fontSize:11))),...done.take(10).map((t)=>ListTile(leading:const Icon(Icons.check_circle,color:OperonTheme.muted),title:Text(t.title),subtitle:Text(t.equipmentTag??'General')))]]),floatingActionButton:FloatingActionButton(onPressed:_add,child:const Icon(Icons.add_alarm)));}
Widget _card(OperatorTimer t){final left=t.dueAt.difference(DateTime.now());return Card(child:Padding(padding:const EdgeInsets.all(4),child:Column(children:[ListTile(leading:Icon(t.due?Icons.notifications_active:Icons.timer,color:t.due?Colors.orange:OperonTheme.teal),title:Text(t.title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${t.equipmentTag??'General'} · ${t.due?(t.acknowledged?'DUE · ACKNOWLEDGED':'DUE · NEEDS ACK'):'${left.inMinutes}m ${left.inSeconds%60}s remaining'}${t.snoozeCount>0?' · snoozed ×${t.snoozeCount}':''}')),if(t.due)Wrap(spacing:6,children:[if(!t.acknowledged)TextButton.icon(onPressed:(){t.acknowledge();_save();setState((){});},icon:const Icon(Icons.visibility),label:const Text('Acknowledge')),TextButton(onPressed:()=>_snooze(t,5),child:const Text('+5m')),TextButton(onPressed:()=>_snooze(t,15),child:const Text('+15m')),FilledButton.icon(onPressed:(){t.complete();_save();setState((){});},icon:const Icon(Icons.check),label:const Text('Complete'))])])));}
void _snooze(OperatorTimer t,int m){t.snooze(Duration(minutes:m));_save();setState((){});}
void _add(){final name=TextEditingController(text:'Check'),tag=TextEditingController();int minutes=30;showDialog(context:context,builder:(x)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('New operator timer'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Reminder')),const SizedBox(height:8),TextField(controller:tag,decoration:const InputDecoration(labelText:'Equipment TAG (optional)')),const SizedBox(height:12),Wrap(spacing:8,children:[5,10,15,30,60].map((m)=>ChoiceChip(label:Text('${m}m'),selected:minutes==m,onSelected:(_)=>set(()=>minutes=m))).toList())]),actions:[FilledButton(onPressed:(){final now=DateTime.now();timers.insert(0,OperatorTimer(id:now.millisecondsSinceEpoch.remainder(2147483647),title:name.text.trim().isEmpty?'Check':name.text.trim(),equipmentTag:tag.text.trim().isEmpty?null:tag.text.trim().toUpperCase(),createdAt:now,dueAt:now.add(Duration(minutes:minutes))));_save();Navigator.pop(c);setState((){});},child:const Text('Start timer'))])));}
}
