import 'dart:async';import 'dart:convert';import 'package:flutter/material.dart';import 'package:shared_preferences/shared_preferences.dart';import '../models/operator_timer.dart';import '../services/notification_service.dart';import '../theme/operon_theme.dart';
class TimersScreen extends StatefulWidget{const TimersScreen({super.key});@override State<TimersScreen> createState()=>_S();}
class _S extends State<TimersScreen>{final timers=<OperatorTimer>[];Timer? tick;static const key='operon.timers.v1';
@override void initState(){super.initState();_load();NotificationService.instance.requestPermissions();tick=Timer.periodic(const Duration(seconds:1),(_)=>_pulse());}
@override void dispose(){tick?.cancel();super.dispose();}
Future<void> _load()async{final p=await SharedPreferences.getInstance(),raw=p.getString(key);if(raw!=null){timers.addAll((jsonDecode(raw) as List).map((e)=>OperatorTimer.fromJson(Map<String,dynamic>.from(e))));}if(mounted)setState((){});}
Future<void> _save()async{final p=await SharedPreferences.getInstance();await p.setString(key,jsonEncode(timers.map((e)=>e.toJson()).toList()));}
void _pulse(){for(final t in timers.where((x)=>!x.acknowledged&&DateTime.now().isAfter(x.dueAt))){t.acknowledged=true;NotificationService.instance.showDue(t.id,t.title,t.equipmentTag);_save();}if(mounted)setState((){});}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Timers & reminders')),body:timers.isEmpty?const Center(child:Text('No timers')):ListView(padding:const EdgeInsets.all(12),children:timers.map((t){final left=t.dueAt.difference(DateTime.now()),due=left.isNegative;return Card(child:ListTile(leading:Icon(due?Icons.notifications_active:Icons.timer,color:due?Colors.orange:OperonTheme.teal),title:Text(t.title),subtitle:Text('${t.equipmentTag??'General'} · ${due?'DUE':'${left.inMinutes}m ${left.inSeconds%60}s remaining'}'),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:(){setState(()=>timers.remove(t));_save();}));}).toList()),floatingActionButton:FloatingActionButton(onPressed:()=>_add(c),child:const Icon(Icons.add_alarm)));
void _add(BuildContext c){final name=TextEditingController(text:'Check'),tag=TextEditingController(),min=TextEditingController(text:'30');showDialog(context:c,builder:(x)=>AlertDialog(title:const Text('New operator timer'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Reminder')),const SizedBox(height:8),TextField(controller:tag,decoration:const InputDecoration(labelText:'Equipment tag (optional)')),const SizedBox(height:8),TextField(controller:min,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Minutes'))]),actions:[FilledButton(onPressed:(){final m=int.tryParse(min.text)??30,now=DateTime.now();setState(()=>timers.insert(0,OperatorTimer(id:now.millisecondsSinceEpoch.remainder(2147483647),title:name.text,equipmentTag:tag.text.trim().isEmpty?null:tag.text.trim().toUpperCase(),createdAt:now,dueAt:now.add(Duration(minutes:m)))));_save();Navigator.pop(x);},child:const Text('Start'))]));}}
